server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: api
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  aop:
    proxy-target-class: true
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fc?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: yourmysqlpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      max-active: 200
      min-idle: 1
      max-wait: 60000
      pool-prepared-statements: false
      validation-query: SELECT 'x'
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 60000
      filters: stat,log4j2,wall
      connection-init-sqls: set names utf8mb4
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 20
        max-wait: 100
        min-idle: 5
        max-idle: 10
        time-between-eviction-runs: 6000
    timeout: 30000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

swagger:
  show: true
qiniu:
  domain: pleaseaddyourdomain
  accessKey: pleaseaddyourkey
  secretKey: pleaseaddyourkey
  bucket: pleaseaddyourbucket

jwt:
  issuer: gym-system
  expiresAt: 2

